// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbonunhnejtfxekffhfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFib251bmhuZWp0Znhla2ZmaGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjUwMzAsImV4cCI6MjA2ODYwMTAzMH0.BAQwGwfjjGD4c_T1YE0KLxSkKHHdwlp-u-7jNOnC5fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});